---
- name: install apache
  apt: name=apache2 state=present  
  vars:
    apache_vhosts_enabled:
      - servername: "vhost1.example.com"
        serveradmin: "admin@example.com"
        documentrootdir: "vhost1.example.com"
        errorlog: "vhost1.example.com"
        customlog: "vhost1.example.com"
      - servername: "vhost2.example.com"
        serveradmin: "admin@example.com"
        documentrootdir: "vhost2.example.com"
        errorlog: "vhost2.example.com"
        customlog: "vhost2.example.com"